# Generated by Django 3.0.1 on 2020-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='subject',
            field=models.TextField(),
        ),
    ]
