# Generated by Django 3.0.1 on 2020-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_auto_20200502_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='name',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='sendername',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='contactdetails',
            table='contactme_contactdetails',
        ),
    ]
