# Generated by Django 3.0.1 on 2020-05-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0003_auto_20200502_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactdetails',
            table='contactdetails',
        ),
    ]
